reference_frame: "map"
goals:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 2.0, 0.0]
timeStep: 0.5
rate: 2.0
navigation:
  safetyMargin: 0.05
  maxError: 0.2
  #arm, pos, orientation, slack, u, q_dot
  weights: [0.5, 10.0, 0.5, 10000000.0, 0.4, 10.0]
  errorWeights: [1.0, 1.0, 1.0]
fineMotion:
  safetyMargin: 0.01
  maxError: 0.1
  weights: [2.5, 50.0, 2.5, 10000000.0, 0.4, 10.0]
  errorWeights: [1.0, 1.0, 1.0]
armMotion:
  # Negative safetyMargin to allow the gripper to get close to the table, sort of a hack
  safetyMargin: -0.2
  maxError: 0.01
  weights: [1.0, 0.0, 0.0, 10000000.0, 10000000.0, 10.0]
  errorWeights: [0.0, 0.0, 1.0]
